### PR TITLE
Add laravel 6 support

### PR DESCRIPTION
**Pull request by doroshenkoss**

### CODE REVIEW

**Comment by vluzrmos** [comment]
Hi @doroshenkoss, thank you for you contribution!

I think we don't need a breaking change where you change "minutes" to "seconds". You can just create a helper method that converts $minutes to a Carbon date, and store on cache. It will avoid some problems when someone try to upgrade laravel-5 to laravel-6 and we may can keep "~5.0|~6.0" on composer.json.

**Note:** You are free to upgrade that PR. ASAP I will test it and make changes on whatever it needs.

Again, Thank you!

**Comment by doroshenkoss** [comment]
Hi! Ok, I'll do that ASAP) Thanks)

**Comment by doroshenkoss** [comment]
Hi @vluzrmos !
Not sure about helper but what do you think about this way? Convert minutes to Carbon instance directly.
Thanks)

**Comment by jdrieghe** [comment]
I'd love to see this PR merged as it's currently blocking us from upgrading our Laravel version. Anything I can do to help out? If you create a new major version release, I'd be happy to test it out immediately.

**Pull request merged**
